# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker



resources:
  repositories:
    - repository: self

trigger: none
pr: none

variables:
  githubToken: $(GITHUB_ACCESS_TOKEN)
  dockerUser: $(DOCKER_USER)
  dockerPassword: $(DOCKER_PASSWORD)
  tenantUrl: $(TENANT_URL)
  userId: $(USER_ID)
  userApiKey: $(USER_API_KEY)
  buildToken: $(BUILD_TOKEN)
  testToken: $(TEST_TOKEN)
  deployToken: $(DEPLOY_TOKEN)
  secureToken: $(SECURE_TOKEN)
  dbUser: $(DB_USER)
  dbPassword: $(DB_PASS)
  # kubeConfig: $(KUBE_CONFIG)
  fq: akscluster-ozdorhhx.hcp.eastus.azmk8s.io
  dbUrl: mysqldb-18d315b1e2c3f3b1e7ca6b0c4e229048.mysql.database.azure.com
  dbName: mysqldb-18d315b1e2c3f3b1e7ca6b0c4e229048
  resourceGroup: rg0802-343ea888-b4ea-93b6-e17d-5abd79a370ec
  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10.12'
        addToPath: true
    - script: |
        echo "FQDN is: $(fq)"
      displayName: 'Echo VARS'
    - script: |
        chmod +x ./pipeline-jenkins/pipeline-jenkins.sh
      displayName: 'Make script executable'
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r ./petstore-catalog-deployment/requirements.txt
      displayName: 'Install dependencies'
    - script: |
        python3 ./pipeline-python/pipeline-jenkins.py --github-token $(githubToken) --docker-user $(dockerUser) --docker-password $(dockerPassword) --tenant-url $(tenantUrl) --user-id $(userId) --user-api-key $(userApiKey) --build-token $(buildToken) --test-token $(testToken) --deploy-token $(deployToken) --secure-token $(secureToken) --db-user $(dbUser) --db-password $(dbPassword) --fqdn $(fq) --db-url $dbUrl --db-name $(dbName) --resource-group $(resourceGroup)
      displayName: 'Run Python script'
