# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker



resources:
  repositories:
    - repository: self

trigger: none

variables:
  githubToken: $(GITHUB_ACCESS_TOKEN)
  dockerUser: $(DOCKER_USER)
  dockerPassword: $(DOCKER_PASSWORD)
  tenantUrl: $(TENANT_URL)
  userId: $(USER_ID)
  userApiKey: $(USER_API_KEY)
  buildToken: $(BUILD_TOKEN)
  testToken: $(TEST_TOKEN)
  deployToken: $(DEPLOY_TOKEN)
  secureToken: $(SECURE_TOKEN)
  orderNumber: $(ORDER_NUMBER)
  fulfillmentId: $(FULFILLMENT_ID)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10.12'
        addToPath: true
    - script: |
        echo "Listing files in the working directory:"
        ls -R
      displayName: 'List files'
    - script: |
        echo $(orderNumber) $(fulfillmentId)
      displayName: 'Echo VARS'
    - script: |
        chmod +x ./pipeline-jenkins/pipeline-jenkins.sh
      displayName: 'Make script executable'
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r ./petstore-catalog-deployment/requirements.txt
      displayName: 'Install dependencies'
    # - script: |
    #     sleep 150 # Timer for 2.5 minutes
    #     echo "Script finished after 2.5 minutes"
    #   displayName: 'Run script with timer'
    - script: |
        python3 ./pipeline-python/pipeline-jenkins.py --github-token $(githubToken) --docker-user $(dockerUser) --docker-password $(dockerPassword) --tenant-url $(tenantUrl) --user-id $(userId) --user-api-key $(userApiKey) --build-token $(buildToken) --test-token $(testToken) --deploy-token $(deployToken) --secure-token $(secureToken) --order-number $(orderNumber) --fulfillment-id $(fulfillmentId)
      displayName: 'Run Python script'
