{{- if not (.Values.isLB) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jpetstoreweb
  namespace: jppetstore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    # Optional: enable gzip for better performance
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
  labels:
    app: jpetstoreweb
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.httpHost }}"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service: 
              name: web
              port:
                number: 80
      
{{- end }}