{{- if not (.Values.isLB) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jpetstoreweb
  namespace: jppetstore
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: jpetstoreweb
spec:
  ingressClassName: nginx
  rules:
  - host: "jpetstore-web.{{ .Values.httpHost }}"
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service: 
              name: web
              port:
                number: 80
      
{{- end }}